using Content.Shared.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Botany.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SeedAnalyzerWindow : DefaultWindow
    {

        private readonly IEntityManager _entityManager;
        private readonly IPrototypeManager _prototypeManager;
        private readonly SeedAnalyzerBoundUserInterface _owner;

        public SeedAnalyzerWindow(SeedAnalyzerBoundUserInterface owner, IEntityManager entityManager, IPrototypeManager prototypeManager)
        {
            RobustXamlLoader.Load(this);
            _entityManager = entityManager;
            _prototypeManager = prototypeManager;
            _owner = owner;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}
